import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box } from "@chakra-ui/react";
// import Navbar from "@/components/Navbar";
import Homedashboard from "@/components/home/Homedashboard";
import Navbar from "@/components/Navbar";
import ParticleBackground from "@/components/particleBackground/Particlebackground";
// import ParticleBackground from "@/components/particleBackground/Particlebackground";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Kremara</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Navbar/>
          <ParticleBackground/>
          <Homedashboard/>
        </Box>
      </main>
    </>
  );
}
